#####
name: CycleGan
bidirect: False #Unidirectional or bidirectional
regist: True    # With or without registration network
noise_level: 0  #  noise level
port: 6019   #  port parameters
save_root: './output/SynthRAD_CycleGAN_noise0_bigbatch_keepratio_512/NC+R/'
#image_save: './output/SynthRAD_CycleGAN_noise0_bigbatch_keepratio_512/NC+R/img/'
image_save: './output/SynthRAD_CycleGAN_noise0_bigbatch_keepratio_512/NC+R/img-residual/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10


epoch: 0        # starting epoch
n_epochs: 80       # How often do you want to display output images during training
batchSize: 8               # size of the batches
dataroot: 'data/SynthRAD2023-Task1/train2D'     # root directory of the dataset
val_dataroot: 'data/SynthRAD2023-Task1/test2D/'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 512                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 32
val_freq: 10 # How often to run validation

resize_mode: keepratio  #keepratio or resize
eval_with_registration: true

# 开启 10 次随机推理，统计均值和标准差
save_uncert_outputs: false
mc_runs: 1                # 次数，默认 1（关闭MC）
mc_mode: input_noise           # 'dropout' 或 'input_noise'
mc_input_noise_sigma: 0.02 # 仅当 mc_mode='input_noise' 时生效；噪声在 [-1,1] 空间

residual_detect: true
rd_fdr_q: 0.10
rd_Tl: 1.5
rd_seed_smooth_sigma: 1.0
rd_seed_min_area_frac: 0.0003
rd_seed_open_r: 1
rd_seed_percentile: 99.5
rd_min_area_frac: 0.0005
rd_bridge_r: 3
rd_open_r: 2
rd_close_r: 2
rd_topk: -1              # -1: 保留全部连通域
rd_seed_dilate: 1        # 种子轻度膨胀（打通细桥）
rd_weight_mode: sigmoid  # 全图软权重（信息更完整）sigmoid or masked
rd_weight_alpha: 1.5
rd_allow_empty: true # 允许空：FDR 无种子时不强行造种子
rd_th_seed_hi: 0 # 硬证据阈值（|z| 的高阈值）
rd_min_highz_pixels: 2 # 最小高像素值计数

# experiment02
metrics_psnr_min: 28.0