#####
# Fusion shared-backbone CycleGAN/RegGAN configuration
trainer: fusion
name: CycleGan-Fusion

port: 6019

# Core architecture flags
bidirect: False            # fusion trainer currently supports only single-direction NC+R
regist: True               # registration network required for NC+R branch
fusion_heads: 3            # number of per-fold heads (must match number of folds)
fusion_default_head: 0     # fallback head when patient id is unmapped
fusion_residual_blocks: 9  # shared trunk residual blocks (matches default CycleGAN)
fusion_confidence: true    # enable dynamic residual-gap confidence weights
fusion_confidence_dir: './output/SynthRAD-RegGAN-fusion3/confidence-weights/'
fusion_confidence_overwrite: false
fusion_confidence_save_components: false
confidence_thr_low: 0.05
confidence_thr_high: 0.15
confidence_gap_max: 0.05
confidence_w_min: 0.05
confidence_lambda_if: 1.0
confidence_lambda_oof: 2.0
confidence_lambda_gap: 1.0

# Data
dataroot: 'data/SynthRAD2023-Task1/train2D-foreground/'
cv_root: 'data/SynthRAD2023-Task1/cv_folds'   # used to assign patients to folds/heads

# Save paths
save_root: './output/SynthRAD-RegGAN-fusion3/NC+R/'
image_save: './output/SynthRAD-RegGAN-fusion3/NC+R/img/'

# Optimisation
epoch: 0
n_epochs: 80
batchSize: 3
lr: 0.0001
decay_epoch: 20
size: 512
input_nc: 1
output_nc: 1
cuda: True
save_every_n_epochs: 5

# Loss weights
Adv_lamda: 1
Corr_lamda: 20
Smooth_lamda: 10

# Dataloader options
noise_level: 0
n_cpu: 4
dataloader_timeout: 60
persistent_workers: true
prefetch_factor: 2
cache_mode: mmap
resize_mode: keepratio

# Validation
val_freq: 5
val_track_enable: true
val_track_fixed_n: 50
val_sample_images: 50
eval_with_registration: true
val_enable_fid: false
val_enable_lpips: false
val_debug_log: false

# Monte Carlo / uncertainty
save_uncert_outputs: false
mc_runs: 1
mc_mode: input_noise
mc_input_noise_sigma: 0.02

# Residual detection (same defaults as best tuned reggan config)
residual_detect: true
rd_fdr_q: 0.05
rd_Tl: 1.8
rd_seed_smooth_sigma: 1.0
rd_seed_min_area_frac: 0.0003
rd_seed_open_r: 1
rd_seed_percentile: 99.5
rd_min_area_frac: 0.0005
rd_bridge_r: 3
rd_open_r: 2
rd_close_r: 2
rd_topk: -1
rd_seed_dilate: 1
rd_weight_mode: sigmoid
rd_weight_alpha: 1.5
rd_allow_empty: true
rd_th_seed_hi: 0
rd_min_highz_pixels: 2

# Residual guidance usage (disabled by default; enables later via checkpoints)
rd_mode: none
rd_mask_dir: ''
rd_weights_dir: ''
rd_w_min: 0.0
rd_cache_weights: false
rd_scan_on_init: false

# Metrics masking flags
metrics_use_rd: false
val_metrics_use_rd: false
test_metrics_use_rd: false

# Logging / W&B
wandb_project: RegGAN
wandb_run_name: RegGAN-fusion3
wandb_tags:
  - SynthRAD2023
  - 512
  - keepratio
  - fusion

# Plotting
test_plot_workers: 8
