#####
name: CycleGan
bidirect: False #Unidirectional or bidirectional
regist: True    # With or without registration network
noise_level: 0  #  noise level
port: 6019   #  port parameters
save_root: './output/SynthRAD-RegGAN-512-keepratio-bestparams-masked/NC+R/'
image_save: './output/SynthRAD-RegGAN-512-keepratio-bestparams-masked/NC+R/img/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10


epoch: 0        # starting epoch
n_epochs: 80       # How often do you want to display output images during training
batchSize: 8               # size of the batches
dataroot: 'data/SynthRAD2023-Task1/train2D'     # root directory of the dataset
val_dataroot: 'data/SynthRAD2023-Task1/test2D/'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 512                # size of the data crop
input_nc: 1
output_nc: 1
cuda: True
n_cpu: 4                 # 或者 8~12，视CPU核数而定；单卡训练通常 4~12 都OK
dataloader_timeout: 30
persistent_workers: true
prefetch_factor: 2
val_freq: 10 # How often to run validation

val_track_enable: true        # 开关
val_track_fixed_n: 50         # 固定追踪的样本数（默认 50）

resize_mode: keepratio  #keepratio or resize
eval_with_registration: true

# 开启 10 次随机推理，统计均值和标准差
save_uncert_outputs: false
mc_runs: 1                # 次数，默认 1（关闭MC）
mc_mode: input_noise           # 'dropout' 或 'input_noise'
mc_input_noise_sigma: 0.02 # 仅当 mc_mode='input_noise' 时生效；噪声在 [-1,1] 空间

# --- WandB logging (optional) ---
# 设置 project / run 名称 / tags 等；留空将使用默认取值
wandb_project: reg-gan
#wandb_run_name: SynthRAD-512-mask
#wandb_tags: [SynthRAD2023, 512, masked]
#wandb_notes: ""

# === Residual detect (best from tune) ===
residual_detect: true
rd_fdr_q: 0.05              # **从 0.10 改为 0.05**
rd_Tl: 1.8                  # **从 1.5 改为 1.8**
rd_seed_smooth_sigma: 1.0
rd_seed_min_area_frac: 0.0003
rd_seed_open_r: 1
rd_seed_percentile: 99.5
rd_min_area_frac: 0.0005
rd_bridge_r: 3
rd_open_r: 2
rd_close_r: 2
rd_topk: -1
rd_seed_dilate: 1
rd_weight_mode: sigmoid
rd_weight_alpha: 1.5
rd_allow_empty: true
rd_th_seed_hi: 0
rd_min_highz_pixels: 2

# === Residual detect usage ===
# rd_mode 取值：none / mask / weights
#   none    → 不加载任何 residual guidance
#   mask    → 从 rd_mask_dir 读取布尔掩膜（1=剔除），内部自动转换成 keep 权重
#   weights → 从 rd_weights_dir 读取 [0,1] 软权重；若该目录为空，则回退 rd_mask_dir
rd_mode: mask
# 使用 mask 时填写生成的掩膜目录；weights 模式会优先使用 rd_weights_dir
rd_mask_dir: ./output/SynthRAD_CycleGAN_noise0_bigbatch_keepratio_512/NC+R/img-residual-bestparams/rd_masks
rd_weights_dir: ./output/SynthRAD_CycleGAN_noise0_bigbatch_keepratio_512/NC+R/img-residual-bestparams/rd_weights
# weights 模式可设置最小权重下限，防止训练时 loss 归零；mask 模式下该值会被忽略
rd_w_min: 0.0
